---
title: "day 2 computationa Session"
format: html
editor: visual
execute: 
  warning: false
  message: false

---
```{r}
library(tidyverse)
```

### Vector
```{r}
# Create a vector

dogs <- c("teddy", "khora", "waffle", "banjo", "tallie")

# Check the class
class(dogs)
```
```{r}
cats <- c("creamsicle wolf", 14.2, 3L)
class(cats)
```
```{r}
years <- c(20, 40, 16, 2)
class (years)
typeof(years)
```
```{r}
# want to do a conditiona check
# is. <<< questions "is this THIS"
# as. <<< gives a command "make this THIS"

is.numeric(years)
is.character(years)
```
```{r}
dog_food <- c(teddy = "purina", khora = "alpo", waffle = "fancy fast")

dog_food
dog_food[2]
dog_food["khora"]

# puedes buscar directamente 
```
```{r}
cars <- c("blue", "orange", "white")

cars[1]

i <- seq(1:2)

cars[i]


```


#se puede cambiar tambien un valor
```{r}
cars[3] <- "yellow"

cars


```
```{r}
fish_size <- matrix (c(12, 14, 18, 20), ncol = 2, nrow = 2, byrow = FALSE)

# Example indexing:
class(fish_size)
typeof(fish_size)

fish_size [1,1]
fish_size [2,1]

# what happens if we create a matrix with different types of data?

fish_type <- matrix (c(12, "trout", 18, 13), ncol = 2, nrow = 2, byrow = FALSE)
class(fish_type)
typeof(fish_type)

# what happens if you have not indicate

fish_size[2,]

fish_size[,2]

```
### List

Reminder : A list combines vectors that can be of different length and type

```{r}
urchins <- list("blue", c(1,2,3), c("a cat", "a dog"), 5L)


urchins_1 <- urchins[3]

class(urchins_1)

urchins_2 <-urchins[[3]]
```


```{r}
tacos <- list (topping = c("onion", "cilantro", "guacamole"),
               filling = c("beans", "meat", "veggies"),
               price = c(6.75, 8.24, 9.50)
               )

tacos

# Index list elements by name

tacos$filling [2]


```
```{r}
a <- c(1,2,3)
b <- c(3,4,5)

my_ttest <- t.test(a, b)

class(my_ttest)

```

the price of a veggie burrito with guacamole is `r tacos$filling[2]`


### Dataframe WORK

```{r}
topping <- c("onion", "cilantro", "guacamole")
filling <- c("beans", "meat", "veggies")
price <- c(6.75, 8.25, 9.50)

df_ex_1 <- data.frame(topping, filling, price)

class(df_ex_1)

df_ex_2 <- data.frame(topping = c("sour_cream", "salsa", "cheese"),
                      filling = c("chicken", "cheese", "cabbage"),
                      price = c(12.50, 13.75, 15.50))
df_ex_3 <- tribble(
  ~topping, ~filling, ~price,
  "avocado", "steak", 13.25,
  "radish", "fish", 10.40,
  "salsa", "veggies", 9.75
)

class(df_ex_3)
```
# Access to dataframe

```{r}
df_ex_3$price[3]
```

